import Form from "./Form";
import {
  Drawer,
  DrawerClose,
  DrawerContent,
  DrawerDescription,
  DrawerFooter,
  DrawerHeader,
  DrawerTitle
} from "@/components/ui/drawer";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { Spinner } from "@/components/ui/spinner";

import heartIcon from "./assets/heart_icon.png";
import sleepIcon from "./assets/sleep_icon.png";
import leafIcon from "./assets/leaf_icon.png";

import './Form.css';

function FormPage() {
  const setValues = (output) => {
    if (output.heart == 0) {
      setHeart("Low");
      setHeartDesc(
        "Based on the input patterns you provided, the model suggests a lower risk related to heart health. This does not confirm medical safety and should be treated as an indicative outcome, not a clinical diagnosis or professional advice."
      );
    } else {
      setHeart("High");
      setHeartDesc(
        "Based on observed patterns in your data, the model indicates a higher potential risk related to heart health. This result is generated by an ML model and should not be considered a confirmed medical condition."
      );
    }

    if (output.metabolism == 0) {
      setMeatabolic("Low");
      setMetaDesc(
        "The model detected patterns that align with a lower metabolic syndrome risk. This outcome reflects statistical tendencies in the data and does not replace medical evaluation or personalized health assessment."
      );
    } else {
      setMeatabolic("High");
      setMetaDesc(
        "According to the data patterns analyzed, the model suggests a higher likelihood of metabolic imbalance. This is an AI-based estimation and should be interpreted carefully, not as a medical conclusion."
      );
    }

    if (output.sleep == 0) {
      setSleep("Healthy");
      setSleeptDesc(
        "The sleep-related patterns in your input align with generally healthy sleep behavior. This insight is generated by a predictive model and may not fully capture real-world sleep conditions."
      );
    } else if (output.sleep == 1) {
      setSleep("Insomnia");
      setSleeptDesc(
        "The model identified patterns commonly associated with disrupted or insufficient sleep. This is a probabilistic ML output and should not be taken as a confirmed sleep disorder diagnosis."
      );
    } else {
      setSleep("Sleep Apnea");
      setSleeptDesc(
        "Based on the provided data patterns, the model suggests indicators that may relate to sleep apnea tendencies. This result is informational only and should not be treated as a medical assessment."
      );
    }
  };


  const getOutput = (output) => {
    setValues(output)
    setTimeout(() => {
      setLoading(false);
    }, 3000);
  }

  let [open, setOpen] = useState(false);
  let [loading, setLoading] = useState(false);
  let [heart, setHeart] = useState("");
  let [sleep, setSleep] = useState("");
  let [metabolic, setMeatabolic] = useState("");
  let [heartDesc, setHeartDesc] = useState("");
  let [sleepDesc, setSleeptDesc] = useState("");
  let [metaDesc, setMetaDesc] = useState("");

  return (
    <>
    <Form getOutput={getOutput} open={setOpen} load={setLoading}/>
      <Drawer open={open} onOpenChange={setOpen} className="dr">
          <DrawerContent>
            <DrawerHeader className="flex-shrink-0">
              <DrawerTitle>Your Health Report</DrawerTitle>
              <DrawerDescription>
                Based on the information given by you
              </DrawerDescription>
            </DrawerHeader>
            <div className="drawer-content flex-1 overflow-y-auto px-4 pb-4">
            {
              loading? (
                <div className="spinner">
                  <Spinner className="size-8" />
                  <p>Loading, it may take some some seconds</p>
                </div>
              ) : (
                <div className="output-box">
                  <div className="output-box-inner">
                    <img src={heartIcon} alt="" className="output-icons"/>
                    &nbsp;&nbsp;&nbsp;
                    <div className="output-content">
                    <h2 style={{color: "#fa0462"}}>Heart Disease chances: {heart}</h2>
                    <p>{heartDesc}</p>
                    </div>
                  </div>
                  <div className="output-box-inner">
                    <img src={sleepIcon} alt="" className="output-icons"/>
                    &nbsp;&nbsp;&nbsp;
                    <div className="output-content">
                    <h2 style={{color: "#0438a0"}}>Sleep Health: {sleep}</h2>
                    <p>{sleepDesc}</p>
                    </div>
                  </div>
                  <div className="output-box-inner">
                    <img src={leafIcon} alt="" className="output-icons"/>
                    &nbsp;&nbsp;&nbsp;
                    <div className="output-content">
                    <h2 style={{color: "#196c00"}}>Metabolic Syndrome risk: {metabolic}</h2>
                    <p>{metaDesc}</p>
                    </div>
                  </div>
              </div>
              )
            }
            </div>
            <DrawerFooter className="flex-shrink-0 sticky bottom-0 bg-background border-t">
              <DrawerClose asChild>
                <Button variant="outline">Close</Button>
              </DrawerClose>
            </DrawerFooter>
          </DrawerContent>
        </Drawer>
    </>
  )
}

export default FormPage;